# Generated by Django 4.1.2 on 2022-11-09 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("description", models.TextField(default="")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=256)),
                ("description", models.TextField(default="")),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "S"), ("M", "M"), ("L", "L")],
                        default="M",
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="splus.category"
                    ),
                ),
            ],
        ),
    ]
